server:
  port: 8084

spring:
  application:
    name: file-storage-server
  servlet:
    multipart:
      enabled: true
      location: ./file-storage-server/upload
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
