global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-server:8071' ]
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8070' ]
  - job_name: 'counsel-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'counsel-server:8080' ]
  - job_name: 'application-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'application-server:8081' ]
  - job_name: 'terms-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'terms-server:8082' ]
  - job_name: 'accept-terms-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'accept-terms-server:8083' ]
  - job_name: 'file-storage-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'file-storage-server:8084' ]
  - job_name: 'judgement-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'judgement-server:8085' ]
  - job_name: 'entry-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'entry-server:8086' ]
  - job_name: 'balance-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'balance-server:8087' ]
  - job_name: 'repayment-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'repayment-server:8088' ]
  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]