CREATE TABLE IF NOT EXISTS `counsel` (
    `counsel_id` int AUTO_INCREMENT  PRIMARY KEY,
    `firstname` varchar(100) NOT NULL,
    `lastname` varchar(100) NOT NULL,
    `address1` varchar(100) NOT NULL,
    `address2` varchar(100) NOT NULL,
    `city` varchar(50) NOT NULL,
    `state` varchar(50) NOT NULL,
    `zip_code` varchar(10) NOT NULL,
    `cell_phone` varchar(10) NOT NULL,
    `email` varchar(100) NOT NULL,
    `memo` text NOT NULL,
    `applied_at` date NOT NULL,
    `communication_status` VARCHAR(50) DEFAULT NULL,
    `created_at` date NOT NULL,
    `created_by` varchar(20) NOT NULL,
    `updated_at` date DEFAULT NULL,
    `updated_by` varchar(20) DEFAULT NULL,
    `is_deleted` boolean DEFAULT false
);
