services:
  counsel-server:
    image: "counsel-server:1.0"
    container_name: "counsel-server-ms"
    ports:
      - "8080:8080"
    env_file:
      - "../../counsel-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  application-server:
    image: "application-server:1.0"
    container_name: "application-server-ms"
    ports:
      - "8081:8080"
    env_file:
      - "../../application-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  terms-server:
    image: "terms-server:1.0"
    container_name: "terms-server-ms"
    ports:
      - "8082:8080"
    env_file:
      - "../../terms-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  accept-terms-server:
    image: "accept-terms-server:1.0"
    container_name: "accept-terms-server-ms"
    ports:
      - "8083:8080"
    env_file:
      - "../../accept-terms-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  file-storage-server:
    image: "file-storage-server:1.0"
    container_name: "file-storage-server-ms"
    ports:
      - "8084:8080"
    extends:
      file: common-config.yml
      service: microservice-base-config

  judgement-server:
    image: "judgement-server:1.0"
    container_name: "judgement-server-ms"
    ports:
      - "8085:8080"
    env_file:
      - "../../judgement-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  entry-server:
    image: "entry-server:1.0"
    container_name: "entry-server-ms"
    ports:
      - "8086:8080"
    env_file:
      - "../../entry-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  balance-server:
    image: "balance-server:1.0"
    container_name: "balance-server-ms"
    ports:
      - "8087:8080"
    env_file:
      - "../../balance-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

  repayment-server:
    image: "repayment-server:1.0"
    container_name: "repayment-server-ms"
    ports:
      - "8088:8080"
    env_file:
      - "../../repayment-server/.env"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  ms-loan:
    driver: "bridge"